const SAVE_NEW_USER = "Save new user failed";
const WELCOME_MESSAGE = " Thank you for using AskMe, the AI powered virtual study assistant.\n\n*Please Read* As a free user you are limited to 5 free request/message per month (1 per day).\n . *Simply* ask any question and wait for a response. If the response is incomplete you can just say \"continue\". \n *To subscribe send the word Topup*"
const TOPUP_ERROR_MESSAGE = "To begin the topup process reply with \"topup\" ";
const TOO_MANY_REQUESTS_TRY_LATER = `*Error*, you have made too many requests within a short space of time, Wait at least 1 minute!!`;
const DO_NOT_SEND_THANK_YOU = "*System message*\n Thank you for using AskMe. Do not send greeting messages or messages such as thank you or you are welcome etc... They will use up your quota";
const USE_THESE_KEY_WORDS = "Use these keywords to access features avaiable to subscribed user\n*createDoc* to create and download word documents from Askme_ai\n*createImage* to create an image provide a description of what you would want,\n*syllabus* : to download a Zimsec syalbaus, supply the subject and the number\n*topup:* to subscribe or topup";
const BE_PATIENT_WHILE_SYSTEM_GENERATES_DOC = "Please be patient while system generates your docx file"
const ERROR_NO_QUOTED_MESSAGES_FOUND = "*Error!! No quoted message found*\n If you would like to *download a word document* from the response generated by Askme , simply *reply* (by swiping right or click on reply arrow on the message with the content) and  *create doc* This will allow you to save what AskMe has given you in a word document . Watch this demonstration on our Tiktok https://vm.tiktok.com/ZM25Htygr/)"
const NO_MEDIA_REQUEST_SEND_TEXT = "Our apologies, current version is not yet able to process media such as images and audio, please make a textual request";
const MESSAGE_FLAGGED = "Sorry!,Your request has been flagged because it has words identified as having potential to be used for illicit/immoral uses and has been sent to the adminstrator for review. If you feel you have been wrongly flagged do appeal to our admin on this number 0775231426";
const ONLY_AVAILABLE_FOR_SUBSCRIBED = "Sorry this service is only available for subscribed users, reply with *Topup*";
const NOT_ENOUGH_CALLS_TO_PROCESS_IMAGE = "Sorry you do not have enough calls remaing today to make this request. Image generation requires 10 or more remain calls per day"
const WAIT_WHILE_MESSAGE_IS_BEING_PROCESSED = "Please wait while your image is being processed, This may take several minutes, please do not send any other message before it finishes. Image generation is equivalent to 15 messages on your quota";
const GENERATED_BY_ASKME_AI = "Generated by Askme_AI";
const WARNING_DO_NOT_SEND_ANY_MORE_MESSAGES = "*Warning , do not send any further messages else you will be blocked from using the platform for at least 48 hours* \nYou have used up your quota. Subscribe to get standard user privileges or Try again tommorow! ";
const BLOCKED_MESSAGE = "You have now been *blocked* for abusing the system and will not be able to use the platform for the next 48 hours, Further messages will result in permanent blocking ";
const SUBSCRIPTION_QUOTA_EXCEDED = "*Do not reply* You have exceeded your quota.Your subscription has a total of 25 requests per day.";
const UNABLE_TO_PROCESS_REQUEST = "Sorry system was unable to complete your request";
const MESSAGE_TOO_LONG = "Your message is too long. Upgrade to subscription service if you want longer scope and higher quotas. You can break it down into smaller bits or summarise.";
const NO_CONTEXT_TO_CONTINUE = "I can only continue based on previous 3 messages if they were made within the last 3 minutes";
const FREE_QUOTA_EXCEDED = "You have exceed your free usage. Reply with the word \"Topup\" to subscribe. Subscription only costs RTGS500 for a 3 day subscription and RTGS6000 (Ecocash) for monthly subscription "
const ECOCASH_NUMBER = "Please send us the ecocash number you would like to pay with";
const INVALID_ECOCASH_NUMBER = "The number you entered is not a valid Econet number\nplease use format shown"
const TOPUP_PRODUCT = "Reply with the product that you want to topup\n1.monthly\n2.payu\nMonthly subscription costs RTGS$6000 and you get 25 messages per day, for 1 month\nPay as you use (payu) costs RTGS$500 and you get 55 messages that you can use over 3 days/72 hours "
const REPLY_WITH_TOPUP = "You are currently using a free quota\nSend the word \"Topup\" to subscribe for more messages/requests"
const INVALID_TOPUP_PRODUCT = `Your topup could not be captured because you did not specify which *product* between 1.payu 2.monthly`
module.exports = {
    USE_THESE_KEY_WORDS, FREE_QUOTA_EXCEDED, REPLY_WITH_TOPUP, INVALID_TOPUP_PRODUCT, INVALID_ECOCASH_NUMBER, TOPUP_PRODUCT, ECOCASH_NUMBER, TOO_MANY_REQUESTS_TRY_LATER, ONLY_AVAILABLE_FOR_SUBSCRIBED, ERROR_NO_QUOTED_MESSAGES_FOUND, BE_PATIENT_WHILE_SYSTEM_GENERATES_DOC, DO_NOT_SEND_THANK_YOU, WARNING_DO_NOT_SEND_ANY_MORE_MESSAGES, GENERATED_BY_ASKME_AI, WAIT_WHILE_MESSAGE_IS_BEING_PROCESSED, SAVE_NEW_USER, TOPUP_ERROR_MESSAGE, TOP_UP_MESSAGE: FREE_QUOTA_EXCEDED, UNABLE_TO_PROCESS_REQUEST, MESSAGE_FLAGGED, MESSAGE_TOO_LONG, SUBSCRIPTION_QUOTA_EXCEDED, NOT_ENOUGH_CALLS_TO_PROCESS_IMAGE, NO_CONTEXT_TO_CONTINUE, NO_MEDIA_REQUEST_SEND_TEXT, BLOCKED_MESSAGE
}




