name: Update app on VM and restart using updated code

on:
  push:
    branches: [main, staging]
    paths:
      - src/**
      - 'package.json'
      - .github/**
      - './*'
      - 'package.json'
      - .github/**
      - './**'
      - '.**'
      - '/**'

env:
  AWS_EC2_PRIVATE_KEY: ${{secrets.AWS_EC2_PRIVATE_KEY}}
  EC2_URL: ${{secrets.EC2_URL}}
  EC2_USERNAME: ${{secrets.EC2_USERNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > mackawaraaws.pem
          chmod 600 mackawaraaws.pem
      - name: SSH into EC2 VM and reset local repo to align to origin
        run: |
          ssh -o StrictHostKeyChecking=no -i  mackawaraaws.pem $EC2_USERNAME@$EC2_URL 'cd repos/askme && git checkout staging  && git fetch --all && git reset --hard origin/staging'
      - name: Restart app using pm2
        run: |
          ssh -o StrictHostKeyChecking=no -i  mackawaraaws.pem $EC2_USERNAME@$EC2_URL 'cd repos/askme && pm2 start index.js --name askme'

#setup-ssh:
#runs-on: ubuntu-latest
#env:
#AWS_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
#EC2_URL: ${{ secrets.EC2_URL }}
#EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
#steps:
#- name: Setup SSH for EC2
#uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
#with:
#EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
#EC2_URL: $EC2_URL
#- name: Get into repos
#run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "cd repos/askme"
#- name: Pull latest changes
#run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "git pull origin main"
#- name: Restart using pm2
#run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL "pm2 restart marketing
